### ISSUE TITLE
Answer format displaying oddly

### ISSUE THREAD

**Issue by HollyRC** [alphagov/govuk-import-export-prototype#32]
Hi Erik,

The answer format doesn't seem to be displaying properly - it doesn't seem to be showing spacing correctly. Not a big deal, but I thought I'd let you know.

Cheers,

Holly

**Comment by erkde** [comment]
It looks like I missed a closing tag in the template, thanks for reporting!

**Comment by erkde** [comment]
This should be ok now, e.g: http://govuk-import-export.herokuapp.com/export-insurance-export-finance.html

**Comment by erkde** [comment]
@HollyRC - can I close this issue, or still seeing weird formatting?
